### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by hama73** [Mkhlf/Keep-It-Flow#4]
I used to avoid having music in the background while watching lectures since I had to constantly jump between tabs, especially on Firefox. Thank you for automating this task for all of us.

Regarding the issue's title, it would be great if you added a privacy statement and defined what data, if any, is being collected. or simply explain why and what permission is required for this extension.

**Comment by Mkhlf** [comment]
I am glad that you loved it.

Regarding the users’ data we don’t collect anything. All the data the app use (Tabs title and if the tab is playing any sound) are temporary stored locally while using the extension.

**Comment by hama73** [comment]
That's awesome, 

I believe it would be beneficial to the extension's adaptation, if you included this information on the extension's description page in the stores.

It can be written as simple as this:

**Privacy Policy**
This extension doesn’t collect any user data.

 or however else you like.
